---
linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - gosimple
    - govet
    - iface
    - ineffassign
    - staticcheck
    - testifylint
    - unused

linters-settings:
  testifylint:
    enable-all: true