---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-merge-conflict
- repo: https://github.com/golangci/golangci-lint
  rev: v1.63.4
  hooks:
    - id: golangci-lint
